### ISSUE TITLE
Authentication is overcomplicated 

### ISSUE THREAD

**Issue by toadytoad** [nyiyui/qrystal#3]
In node/auth.go, use standard signature schemes. As an example I've added an explanation of how this would work using RSA, however other more secure exchanges like a DHKE + AES_GCM would most likely suffice.

Server and Client want to exchange VPN credentials. Each of them have methods of communicating through public key cryptography. Server encrypts their VPN credentials using Client's public key, and signs the hash of the credentials using the private key. Client does the same with their credentials and sends to Server. An attacker Eve, has the encrypted messages and the signatures, however a replay attack is not possible as even if Eve impersonates either the Client or the Server, she will not be able to actually decrypt the credentials. 

Matching public keys to people is a completely different topic and requires some kind of ID.

**Comment by nyiyui** [comment]
Thank you. This was fixed by removing authn and signing/verifying the individuals requests and responses (46b9939a1f728bd137ebfc8e024953a12de88dde).
